config/routes.rb
Case2::Application.routes.draw do
  devise_for :users
  
  namespace :account do
    resources :users 
  end

  resources :clients
  resources :lawyers
  resources :file_matters do
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_title"
    end
  end
  resources :case_entries do
  	# get :autocomplete_file_matter_file_code, :on => :collection
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_case_number"
    end
      
  end

  resources :admin_side
  resources :graphs do 
    collection do 
      get "ac_file_code"
      get "ac_client_gr"
    end
  end
  resources :calls do
    collection do 
      get "ac_client"
    end
  end

  resources :printouts do
    collection do 
      get "ac_file_code"
    end

  end
  
  resources :notifications do
    collection do
      get "list_notifications"
      get "notified"
    end
  end

  resources :schedules
  resources :practice_tables 
  resources :doc_abbreviations
  resources :file_namings
  resources :case_entry_billings
  
  root :to => 'case_entries#new'
  
  # ajax
  get 'pages/update_songs', :as => 'update_songs'
  get 'pages/update_songs2', :as => 'update_songs2'
  get 'pages/parse_client', :as => 'parse_client'
  get 'pages/update_case_entry', :as => 'update_case_entry'
  get 'pages/printouts_entry', :as => 'printouts_entry'
  get 'pages/update_cases', :as => 'update_cases'
  get 'pages/update_search_form', :as => 'update_search_form'
  get 'pages/schedule_entry', :as => 'schedule_entry'
  get 'pages/add_client_code', :as => 'add_client_code'
  get 'pages/pick_filematter', :as => 'pick_filematter'
  get 'pages/add_practice_code', :as => 'add_practice_code'
  get 'pages/select_file_matters', :as => 'select_file_matters'
  get 'pages/select_status', :as => 'select_status'
  get 'pages/update_status_assinged', :as => 'update_status_assinged'
  

  # search
  # match '/all_employees_list', :to => 'labor_hours#all_employees_list'
  match 'search_entry', :to  => 'case_entries#search_entry'
  match 'search_entry_multi', :to  => 'case_entries#search_entry_multi'
  match 'search_entry_graph', :to  => 'graphs#search_entry_graph'
  match 'search_entry_other_graph', :to  => 'graphs#search_entry_other_graph'
  match 'search_entry_other_graph2', :to  => 'graphs#search_entry_other_graph2'
  match 'exclude_billing', :to =>  'case_entries#exclude_billing'
  match 'modify_case_entry', :to =>  'case_entries#modify_case_entry'
  match 'case_entries/search' => 'case_entries#search_entry'
  match 'file_matters/search' => 'file_matters#search_entry'
  match '/admin_side/search' => 'admin_side#index'
  match 'activate_account', :to =>  'account/users#activate_account'
  match 'deactivate_account', :to =>  'account/users#deactivate_account'
  match 'activate_lawyer', :to =>  'lawyers#activate_account'
  match 'deactivate_lawyer', :to =>  'lawyers#deactivate_account'
  match 'exclude_printout', :to =>  'printouts#exclude_printout'
  match 'include_printout', :to =>  'printouts#include_printout'
  match 'search_by_client', :to => 'printouts#search_by_client'
  match 'weekly_view', :to => 'schedules#weekly_view'
  match 'daily_view', :to => 'schedules#daily_view'
  

  # recent modification for filtering data in case entries
  match 'filter_by_workload', :to => 'case_entries#filter_by_workload'
  match 'filter_by_client_code', :to => 'case_entries#filter_by_client_code'
  match 'filter_by_practice_code', :to => 'case_entries#filter_by_practice_code'
  match 'filter_by_period', :to => 'case_entries#filter_by_period'
  match 'filter_by_compared_workload', :to => 'case_entries#filter_by_compared_workload'

  # for timesheet additional tab and function
  match 'search_billed_entry', :to  => 'case_entries#search_billed_entry'
  match 'mark_as_billed', :to  => 'case_entries#mark_as_billed'

  match 'view_billing_generated', :to => 'case_entry_billings#view_billing_generated'
  match 'assigned_lawyer_filematters', :to => 'pages#assigned_lawyer_filematters'
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
	autocomplete :file_matter, :file_code, :full => true
	autocomplete :client, :name, :full => true
	def index
		if params[:lawyer_id].blank?
			@lawyers = Lawyer.where(:position => "Associate", is_active: 'Yes')
		else
			if params[:lawyer_id] == ["SENIOR ASSOCIATES"]
				@lawyers = Lawyer.where(:position => 'Senior Associate', is_active: 'Yes')
			elsif params[:lawyer_id] == ["ASSOCIATES"]
				@lawyers = Lawyer.where(:position => 'Associate', is_active: 'Yes')
			elsif params[:lawyer_id] == ["PARTNERS"]
				@lawyers = Lawyer.where(:position => 'Partner', is_active: 'Yes')
			elsif params[:lawyer_id] == ["SENIOR PARTNERS"]
				@lawyers = Lawyer.where(:position => 'Senior Partner', is_active: 'Yes')	
			else	
				@lawyers = Lawyer.where(:id => params[:lawyer_id], is_active: 'Yes')
			end
		end	

		if params[:beginning_date].blank?
			@beginning_date = Date.today.beginning_of_month.strftime('%b %d, %Y')
		else
			@beginning_date = Date.parse(params[:beginning_date], '%b %d, %Y')
		end

		if params[:ending_date].blank?
			@ending_date = Date.today.end_of_month.strftime('%b %d, %Y')
		else
			@ending_date = Date.parse(params[:ending_date], '%b %d, %Y')
		end

		# @beginning_date = Date.today.beginning_of_month.strftime('%b %d, %Y')
		# @ending_date = Date.today.end_of_month.strftime('%b %d, %Y')
		# @case_entries = @case_entries = CaseEntry.where(entry_date: @beginning_date..@ending_date)
		@lawyers2 = Lawyer.where(is_active: 'Yes').map{|a|[a.full_name, a.id]}
		@lawyers2 << ['SENIOR ASSOCIATES','SENIOR ASSOCIATES']
		@lawyers2 << ['ASSOCIATES','ASSOCIATES']
		@lawyers2 << ['SENIOR PARTNERS','SENIOR PARTNERS']
		@lawyers2 << ['PARTNERS','PARTNERS']

		
	end

	def search_entry_other_graph
		if params[:file_matter_id].blank? 
			@file_matter_id = FileMatter.all.first
		else
			@file_matter_id = FileMatter.where(:file_code => params[:file_matter_id]).last
			@assigned_lawyers = AssignedLawyer.where(:file_matter_id => @file_matter_id.id)	
			@lawyers2 = Lawyer.where(is_active: 'Yes').map{|a|[a.full_name, a.id]}
		end	

		if params[:beginning_date].blank?
			@beginning_date = Date.today.beginning_of_month.strftime('%b %d, %Y')
		else
			@beginning_date = Date.parse(params[:beginning_date], '%b %d, %Y')
		end

		if params[:ending_date].blank?
			@ending_date = Date.today.end_of_month.strftime('%b %d, %Y')
		else
			@ending_date = Date.parse(params[:ending_date], '%b %d, %Y')
		end
	end

	def search_entry_other_graph2
		@months = Array.new
		if params[:client].blank? 
			@client_id = Client.all.first
		else
			@client_id = Client.where("name ILIKE ?", "#{params[:client]}").last
			# @file_reference = FileMatter.where(:id => params[:file_matter_id])
			# @assigned_lawyers = AssignedLawyer.where(:file_matter_id => params[:file_matter_id])	
			# @lawyers2 = Lawyer.all.map{|a|[a.full_name, a.id]}
		end
		@months << ['January',1]	
		# if params[:beginning_date].blank?
		# 	@beginning_date = Date.today.beginning_of_month.strftime('%b %d, %Y')
		# else
		# 	@beginning_date = Date.parse(params[:beginning_date], '%b %d, %Y')
		# end

		# if params[:ending_date].blank?
		# 	@ending_date = Date.today.end_of_month.strftime('%b %d, %Y')
		# else
		# 	@ending_date = Date.parse(params[:ending_date], '%b %d, %Y')
		# end
	end

	def ac_client_gr
		render json: Client.select("distinct name as value").where("name ILIKE ?", "%#{params[:term]}%")
	end

	def ac_file_code
    render json: FileMatter.select("distinct file_code as value").where("file_code ILIKE ?", "%#{params[:term]}%")
  end
end

app/views/graphs/_bar_graph.html.erb
<% @arr = Array.new %>
<% @arr2 = Array.new %>
<% @lawyers.each do |lawyer| %>
  <% @arr << lawyer.full_name %>
  <% @arr2 << calculate_time(lawyer.id, @beginning_date, @ending_date) %>
<% end %>
<script>
  $(function () {
      $('#container').highcharts({
          chart: {
              type: 'bar'
          },
          title: {
              text: 'Lawyers Work Presentation by Hours'
          },
          subtitle: {
              text: 'Period Covers: <%=raw(@beginning_date)%> - <%=raw(@ending_date)%>'
          },
          xAxis: {
              // categories: ['Africa', 'America', 'Asia', 'Europe', 'Oceania'],
              categories: <%= raw(@arr) %>,
              title: {
                  text: null
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'List Of Lawyers Time Accumulation',
                  align: 'high'
              },
              labels: {
                  overflow: 'justify'
              }
          },
          tooltip: {
              valueSuffix: ' hours'
          },
          plotOptions: {
              bar: {
                  dataLabels: {
                      enabled: true
                  }
              }
          },
          legend: {
              layout: 'vertical',
              align: 'right',
              verticalAlign: 'top',
              x: -40,
              y: 100,
              floating: true,
              borderWidth: 1,
              backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
              shadow: true
          },
          credits: {
              enabled: false
          },
          series: [ //{
              // name: 'Accumulated Hours',
              // data: [107, 31, 835, 203, 2, 50, 33, 23, 34, 12]
              // data: <%= raw(@arr2) %>
          // }
          // }, 

          {
              name: 'Year 1900',
              data: [133, 156, 947, 408, 6, 50, 33, 23, 34, 12]
          }, 

          {
              name: 'Year 2008',
              data: [973, 914, 4054, 732, 34, 50, 33, 23, 34, 12]
          },

          ]
      });
  });
</script>
<div id="container" style="width: 100%; height: 600px; margin: 0 auto"></div>

app/views/graphs/_bar_graph2.html.erb
<% if params[:file_matter_id].nil? %>
<% else %>
  <% @file_matter_case = FileMatter.select('title, file_code').where(file_code: params[:file_matter_id]).last %>
  <% @arr = Array.new %>
  <% @arr2 = Array.new %>
  <% @assigned_lawyers.each do |lawyer| %>
    <% lawyer.lawyer_id %>
    <% @arr << lawyer.lawyer.full_name %>
    <% @arr2 << calculate_time_per_filematter(lawyer.lawyer_id, @beginning_date, @ending_date, params[:file_matter_id].to_s).to_f %>
  <% end %>
  <script>
    $(function () {
        $('#container').highcharts({
            chart: {
                type: 'bar'
            },
            title: {
                text: 'File Reference # <%= raw(@file_matter_case.file_code).upcase %>'
            },
            subtitle: {
                text: '<%= raw(@file_matter_case.title).upcase %> <br/> Period Covers: <%=raw(@beginning_date)%> - <%=raw(@ending_date)%>'
            },
            xAxis: {
                // categories: ['Africa', 'America', 'Asia', 'Europe', 'Oceania'],
                categories: <%= raw(@arr) %>,
                title: {
                    text: null
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'List Of Lawyers Time Accumulation',
                    align: 'high'
                },
                labels: {
                    overflow: 'justify'
                }
            },
            tooltip: {
                valueSuffix: ' hours'
            },
            plotOptions: {
                bar: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -40,
                y: 100,
                floating: true,
                borderWidth: 1,
                backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                shadow: true
            },
            credits: {
                enabled: false
            },
            series: [{
                name: 'Accumulated Hours',
                // data: [107, 31, 835, 203, 2, 50, 33, 23, 34, 12]
                data: <%= raw(@arr2) %>
            }
            // }, 

            // {
            //     name: 'Year 1900',
            //     data: [133, 156, 947, 408, 6, 50, 33, 23, 34, 12]
            // }, 

            // {
            //     name: 'Year 2008',
            //     data: [973, 914, 4054, 732, 34, 50, 33, 23, 34, 12]
            // }

            ]
        });
    });
  </script>
  <div id="container" style="width: 100%; height: 600px; margin: 0 auto"></div>
<% end %>

app/views/graphs/_line_graph.html.erb
<% @arr = Array.new %>
<% @lawyers.each do |lawyer| %>
    <% @arr << [lawyer.full_name, calculate_time(lawyer.id, @beginning_date, @ending_date)] %>
<% end %>
<script>
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Lawyers Work Presentation by Hours'
        },
        subtitle: {
            text: 'Period Covers: <%=raw(@beginning_date)%> - <%=raw(@ending_date)%>'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'List Of Lawyers Time Accumulation'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            pointFormat: 'Lawyers Time Recorded: <b>{point.y:.1f} hours</b>'
        },
        series: [{
            name: 'Lawyers',
            data: <%= raw(@arr) %>,
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                x: 4,
                y: 10,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif',
                    textShadow: '0 0 3px black'
                }
            }
        }]
    });
});
</script>
<div id="container" style="width: 100%; height: 600px; margin: 0 auto"></div>

app/views/graphs/_search_entry.html.erb
<div class="panel panel-primary">
  	<div class="panel-primary panel-heading">Search</div>
	  <div class="row">
	    <div class="span11">
		    <%= form_for search_entry_graph_path, :method => 'get' do %>
			<table class="table" width="100%">
			  <thead>		
				<tr>
					<td>Lawyer List:</td>
					<td colspan=3>
						<%= select_tag :lawyer_id, options_for_select(@lawyers2), { "data-placeholder" => "", :multiple => true, id: 'chosen-select2', :include_blank => true, :style => "width: 100%;"} %>
					</td>
				</tr>	
				<tr>
					<td>Date From: </td>	
					<td>
						<%= text_field_tag :beginning_date, nil,  :id => "datepicker_beg"%>
					</td>
					<td>Date To: </td>	
					<td>
						<%= text_field_tag :ending_date, nil,  :id => "datepicker_end"%>
						<%= hidden_field_tag :pfr, 1%>
					</td>
				</tr>
				<tr><td colspan="4"><div class="pull-right">
					    <%= submit_tag "Search" %>
				</div></td></tr>
			  </thead>		
			</table>
		<% end %>
    	</div>
  	</div>
  </div>
<script>
  $("#chosen-select2").chosen();
  $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
  $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/graphs/_search_entry_cl.html.erb
<div class="panel panel-primary">
  	<div class="panel-primary panel-heading">Search</div>
	  <div class="row">
	    <div class="span11">
		    <%= form_for search_entry_other_graph2_path, :method => 'get' do %>
			<table class="table" width="100%">
			  <thead>		
				<tr>
					<td>Client :</td>
					<td colspan='3'>
						<%= autocomplete_field_tag :client, nil, ac_client_gr_graphs_path, :required => true, :style => "width: 90%;" %>
					</td>
					<!-- <td>Case Title:</td>
					<td>
						<%#= select_tag :file_matter_id, nil, prompt: "Select from List", id: "cases" %>
						
					</td> -->
				</tr>
				<tr>
					<td width="10%">Year :</td>
					<td width="10%">
						<%= select_tag :year, options_for_select(['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017'], :selected => Date.today.year), :style => "width: 100%;" %>
					</td>
					<td width="10%">Month/s: </td>	
					<td width="70%">
						<%= select_tag :month, options_for_select(['January','February','March','April','May','June','July','August','September','October','November','December']), { "data-placeholder" => "", :multiple => true, id: 'chosen-select2', :include_blank => true, :style => "width: 100%;"} %>
						<%= hidden_field_tag :pfr, 3%>
					</td>
				</tr>

				<!-- <tr>
					<td>Date From: </td>	
					<td>
						<%#= text_field_tag :beginning_date, nil,  :id => "datepicker_beg"%>
					</td>
					<td>Date To: </td>	
					<td>
						<%#= text_field_tag :ending_date, nil,  :id => "datepicker_end"%>
						
					</td>
				</tr> -->
				<tr><td colspan="4"><div class="pull-right">
					    <%= submit_tag "Search" %>
				</div></td></tr>
			  </thead>		
			</table>
		<% end %>
    	</div>
  	</div>
  </div>
<script>
	$("#chosen-select2").chosen();
  $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
  $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
  $(document).ready(function(){
      $('#client').blur(function(){
        $.ajax({
          url: "<%= update_cases_path %>",
          data: {
            client : $('#client').val()
          },
          dataType: "script"
          // success: function(data){
          //   console.log(data);
          // }
        });
      });
    }); 
</script>

app/views/graphs/_search_entry_other.html.erb
<div class="panel panel-primary">
  	<div class="panel-primary panel-heading">Search</div>
	  <div class="row">
	    <div class="span11">
		    <%= form_for search_entry_other_graph_path, :method => 'get' do %>
					<table class="table" width="100%">
					  <thead>		
							<tr>
								<td width="12%">File Reference #:</td>
								<td width="12%">
									<%= autocomplete_field_tag :file_matter_id, nil, ac_file_code_graphs_path, :required => true, :style => "width: 90%;" %>
								</td>
								<td width="10%"><center>Date From:</center></td>	
								<td width="15%">
									<%= text_field_tag :beginning_date, nil,  :id => "datepicker_beg", :style => "width: 80%;"%>
								</td>
								<td width="10%"><center>Date To:</center></td>	
								<td width="15%">
									<%= text_field_tag :ending_date, nil,  :id => "datepicker_end", :style => "width: 80%;"%>
									<%= hidden_field_tag :pfr, 2%>
								</td>
								<td><center><%= submit_tag "Search" %></center></td>
							</tr>
					  </thead>		
					</table>
				<% end %>
    	</div>
  	</div>
  </div>
<script>
  $("#chosen-select2").chosen();
  $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
  $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/graphs/index.html.erb
<%= javascript_include_tag "highcharts" %>
<%= javascript_include_tag "modules/exporting" %>
<div class="panel">
  <div class="panel-heading"><h3>Graph</h3></div>
  <ul class="nav nav-tabs">
    <% if params[:pfr] == '1' %>
      <% cl = 'active' %>
    <% else %>
      <% cl = '' %>
    <% end %>

    <% if params[:pfr] == '2' %>
      <% cl2 = 'active' %>
    <% else %>
      <% cl2 = '' %>
    <% end %>

    <% if params[:pfr] == '3' %>
      <% cl3 = 'active' %>
    <% else %>
      <% cl3 = '' %>
    <% end %>

    <li class="<%= cl %>" >
      <%= link_to "Lawyers Hourly Stats", graphs_path(pfr:"1") %>
    </li>
    <li class="<%= cl2 %>" >
      <%= link_to "File Reference Stats", search_entry_other_graph_path(pfr:"2") %>
    </li>
    <li class="<%= cl3 %>" >
      <%= link_to "Client Stats", search_entry_other_graph2_path(pfr:"3") %>
    </li>
  </ul>
  <%= render "search_entry"%>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Representation</div>
    <div class="row">
      <div class="span11">
        <div class="row">
          <div class="pull-right" style="padding-bottom: 20px;">
            <%= link_to "<i class='icon-th'>&nbsp;Bar</i>".html_safe, graphs_path(params.merge(pfr:"1", type:"bar")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Bar", toggle: "modal"} %>
            <%= link_to "<i class='icon-th'>&nbsp;Pie</i>".html_safe, graphs_path(params.merge(pfr:"1", type:"pie")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Pie", toggle: "modal"} %>
            <%= link_to "<i class='icon-th'>&nbsp;Column</i>".html_safe, graphs_path(params.merge(pfr:"1", type:"line")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Column", toggle: "modal"} %>
          </div>
          <div class="span11 well">
            <% if params[:type] == 'bar' %>
              <%= render "bar_graph" %>
            <% elsif params[:type] == 'pie' %>
              <%= render "pie_graph" %>
            <% else %>  
              <%= render "line_graph" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/graphs/search_entry_other_graph.html.erb
<%= javascript_include_tag "highcharts" %>
<%= javascript_include_tag "modules/exporting" %>
<div class="panel">
  <div class="panel-heading"><h3>Graph</h3></div>
    <ul class="nav nav-tabs">
      <% if params[:pfr] == '1' %>
        <% cl = 'active' %>
      <% else %>
        <% cl = '' %>
      <% end %>

      <% if params[:pfr] == '2' %>
        <% cl2 = 'active' %>
      <% else %>
        <% cl2 = '' %>
      <% end %>

      <% if params[:pfr] == '3' %>
        <% cl3 = 'active' %>
      <% else %>
        <% cl3 = '' %>
      <% end %>

      <li class="<%= cl %>" >
        <%= link_to "Lawyers Hourly Stats", graphs_path(pfr:"1") %>
      </li>
      <li class="<%= cl2 %>" >
        <%= link_to "File Reference Stats", search_entry_other_graph_path(pfr:"2") %>
      </li>
      <li class="<%= cl3 %>" >
        <%= link_to "Client Stats", search_entry_other_graph2_path(pfr:"3") %>
      </li>
    </ul>
  <%= render "search_entry_other"%>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Representation</div>
    <div class="row">
      <div class="span11">
        <div class="row">
          <div class="pull-right" style="padding-bottom: 20px;">
            <%= link_to "<i class='icon-th'>&nbsp;Bar</i>".html_safe, search_entry_other_graph_path(params.merge(pfr:"2", type:"bar")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Bar", toggle: "modal"} %>
            <%= link_to "<i class='icon-th'>&nbsp;Pie</i>".html_safe, search_entry_other_graph_path(params.merge(pfr:"2", type:"pie")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Pie", toggle: "modal"} %>
            <%= link_to "<i class='icon-th'>&nbsp;Column</i>".html_safe, search_entry_other_graph_path(params.merge(pfr:"2", type:"line")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Column", toggle: "modal"} %>
          </div>
          <div class="span11 well">
            <% if params[:type] == 'bar' %>
              <%= render "bar_graph2" %>
            <% elsif params[:type] == 'pie' %>
              <%= render "pie_graph2" %>
            <% else %>  
              <%= render "line_graph2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/graphs/search_entry_other_graph2.html.erb
<%= javascript_include_tag "highcharts" %>
<%= javascript_include_tag "modules/exporting" %>
<div class="panel">
  <div class="panel-heading"><h3>Graph</h3></div>
    <ul class="nav nav-tabs">
      <% if params[:pfr] == '1' %>
        <% cl = 'active' %>
      <% else %>
        <% cl = '' %>
      <% end %>

      <% if params[:pfr] == '2' %>
        <% cl2 = 'active' %>
      <% else %>
        <% cl2 = '' %>
      <% end %>

      <% if params[:pfr] == '3' %>
        <% cl3 = 'active' %>
      <% else %>
        <% cl3 = '' %>
      <% end %>

      <li class="<%= cl %>" >
        <%= link_to "Lawyers Hourly Stats", graphs_path(pfr:"1") %>
      </li>
      <li class="<%= cl2 %>" >
        <%= link_to "File Reference Stats", search_entry_other_graph_path(pfr:"2") %>
      </li>
      <li class="<%= cl3 %>" >
        <%= link_to "Client Stats", search_entry_other_graph2_path(pfr:"3") %>
      </li>
    </ul>
  <%= render "search_entry_cl"%>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Representation</div>
    <div class="row">
      <div class="span11">
        <div class="row">
          <div class="pull-right" style="padding-bottom: 20px;">
            <%= link_to "<i class='icon-th'>&nbsp;Bar</i>".html_safe, search_entry_other_graph2_path(params.merge(pfr:"3", type:"bar")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Bar", toggle: "modal"} %>
            <%= link_to "<i class='icon-th'>&nbsp;Pie</i>".html_safe, search_entry_other_graph2_path(params.merge(pfr:"3", type:"pie")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Pie", toggle: "modal"} %>
            <%= link_to "<i class='icon-th'>&nbsp;Column</i>".html_safe, search_entry_other_graph2_path(params.merge(pfr:"3", type:"line")), class: "btn btn-xs btn-info", data: {rel: "tooltip", title: "Column", toggle: "modal"} %>
          </div>
          <div class="span11 well">
            <% if params[:type] == 'bar' %>
              <%= render "bar_graph3" %>
            <% elsif params[:type] == 'pie' %>
              <%= render "pie_graph3" %>
            <% else %>  
              <%= render "line_graph3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>