config/routes.rb
Case2::Application.routes.draw do
  devise_for :users
  
  namespace :account do
    resources :users 
  end

  resources :clients
  resources :lawyers
  resources :file_matters do
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_title"
    end
  end
  resources :case_entries do
  	# get :autocomplete_file_matter_file_code, :on => :collection
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_case_number"
    end
      
  end

  resources :admin_side
  resources :graphs do 
    collection do 
      get "ac_file_code"
      get "ac_client_gr"
    end
  end
  resources :calls do
    collection do 
      get "ac_client"
    end
  end

  resources :printouts do
    collection do 
      get "ac_file_code"
    end

  end
  
  resources :notifications do
    collection do
      get "list_notifications"
      get "notified"
    end
  end

  resources :schedules
  resources :practice_tables 
  resources :doc_abbreviations
  resources :file_namings
  resources :case_entry_billings
  
  root :to => 'case_entries#new'
  
  # ajax
  get 'pages/update_songs', :as => 'update_songs'
  get 'pages/update_songs2', :as => 'update_songs2'
  get 'pages/parse_client', :as => 'parse_client'
  get 'pages/update_case_entry', :as => 'update_case_entry'
  get 'pages/printouts_entry', :as => 'printouts_entry'
  get 'pages/update_cases', :as => 'update_cases'
  get 'pages/update_search_form', :as => 'update_search_form'
  get 'pages/schedule_entry', :as => 'schedule_entry'
  get 'pages/add_client_code', :as => 'add_client_code'
  get 'pages/pick_filematter', :as => 'pick_filematter'
  get 'pages/add_practice_code', :as => 'add_practice_code'
  get 'pages/select_file_matters', :as => 'select_file_matters'
  get 'pages/select_status', :as => 'select_status'
  get 'pages/update_status_assinged', :as => 'update_status_assinged'
  

  # search
  # match '/all_employees_list', :to => 'labor_hours#all_employees_list'
  match 'search_entry', :to  => 'case_entries#search_entry'
  match 'search_entry_multi', :to  => 'case_entries#search_entry_multi'
  match 'search_entry_graph', :to  => 'graphs#search_entry_graph'
  match 'search_entry_other_graph', :to  => 'graphs#search_entry_other_graph'
  match 'search_entry_other_graph2', :to  => 'graphs#search_entry_other_graph2'
  match 'exclude_billing', :to =>  'case_entries#exclude_billing'
  match 'modify_case_entry', :to =>  'case_entries#modify_case_entry'
  match 'case_entries/search' => 'case_entries#search_entry'
  match 'file_matters/search' => 'file_matters#search_entry'
  match '/admin_side/search' => 'admin_side#index'
  match 'activate_account', :to =>  'account/users#activate_account'
  match 'deactivate_account', :to =>  'account/users#deactivate_account'
  match 'activate_lawyer', :to =>  'lawyers#activate_account'
  match 'deactivate_lawyer', :to =>  'lawyers#deactivate_account'
  match 'exclude_printout', :to =>  'printouts#exclude_printout'
  match 'include_printout', :to =>  'printouts#include_printout'
  match 'search_by_client', :to => 'printouts#search_by_client'
  match 'weekly_view', :to => 'schedules#weekly_view'
  match 'daily_view', :to => 'schedules#daily_view'
  

  # recent modification for filtering data in case entries
  match 'filter_by_workload', :to => 'case_entries#filter_by_workload'
  match 'filter_by_client_code', :to => 'case_entries#filter_by_client_code'
  match 'filter_by_practice_code', :to => 'case_entries#filter_by_practice_code'
  match 'filter_by_period', :to => 'case_entries#filter_by_period'
  match 'filter_by_compared_workload', :to => 'case_entries#filter_by_compared_workload'

  # for timesheet additional tab and function
  match 'search_billed_entry', :to  => 'case_entries#search_billed_entry'
  match 'mark_as_billed', :to  => 'case_entries#mark_as_billed'

  match 'view_billing_generated', :to => 'case_entry_billings#view_billing_generated'
  match 'assigned_lawyer_filematters', :to => 'pages#assigned_lawyer_filematters'
end

app/views/partials/_flash.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <br>
    <div class="span4"></div>    
    <div class="span3 alert alert-<%= flash_class(level) %>" id="flash">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <%= content_tag :p, flash[level] %>
    </div>
    <div class="span4"></div>
  <% end %>
<% end %>

app/views/partials/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Time Entry</a>
      <div class="nav-collapse">
        <% if user_signed_in? %>
          <ul class="nav">
            <% if current_user.role != 'User' %>
              <li><%= link_to "Case Entries", case_entries_path %></li>
              <li><%= link_to "Clients", clients_path %></li>
              <li><%= link_to "Lawyers", lawyers_path %></li>
              <li><%= link_to "File/Matters", file_matters_path %></li>
              <!-- <li>
                <%#= link_to "Reports", admin_side_index_path %>
              </li> -->
              <li>  
                <%= link_to "Timesheet", search_entry_path %>
              </li>
              <li>  
                <%= link_to "Users", account_users_path %>
              </li>
              <li>  
                <%= link_to "Graphs", graphs_path %>
              </li>
            <% else %>
              <li><%= link_to "Case Entries", case_entries_path %></li>
              <li><%= link_to "File/Matters", file_matters_path %></li>
            <% end %>

          </ul>

          <ul class="nav pull-right">
            <li>
              <%= link_to current_user.name, edit_user_registration_path(current_user) %>
            </li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/partials/_sidenav.html.erb
<div id="sidebar-nav">
        <ul id="dashboard-menu">
            <li class="active">
                <div class="pointer">
                    <div class="arrow"></div>
                    <div class="arrow_border"></div>
                </div>
                <a href="index.html">
                    <i class="icon-home"></i>
                    <span>Home</span>
                </a>
            </li>            
            <li>
                <a href="chart-showcase.html">
                    <i class="icon-signal"></i>
                    <span>Charts</span>
                </a>
            </li>
            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-group"></i>
                    <span>Users</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="user-list.html">User list</a></li>
                    <li><a href="new-user.html">New user form</a></li>
                    <li><a href="user-profile.html">User profile</a></li>
                </ul>
            </li>
            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-edit"></i>
                    <span>Forms</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="form-showcase.html">Form showcase</a></li>
                    <li><a href="form-wizard.html">Form wizard</a></li>
                </ul>
            </li>
            <li>
                <a href="gallery.html">
                    <i class="icon-picture"></i>
                    <span>Gallery</span>
                </a>
            </li>
            <li>
                <a href="calendar.html">
                    <i class="icon-calendar-empty"></i>
                    <span>Calendar</span>
                </a>
            </li>
            <li>
                <a class="dropdown-toggle" href="tables.html">
                    <i class="icon-th-large"></i>
                    <span>Tables</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="tables.html">Custom tables</a></li>
                    <li><a href="datatables.html">DataTables</a></li>
                </ul>
            </li>
            <li>
                <a class="dropdown-toggle ui-elements" href="#">
                    <i class="icon-code-fork"></i>
                    <span>UI Elements</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="ui-elements.html">UI Elements</a></li>
                    <li><a href="icons.html">Icons</a></li>
                </ul>
            </li>
            <li>
                <a href="personal-info.html">
                    <i class="icon-cog"></i>
                    <span>My Info</span>
                </a>
            </li>
            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-share-alt"></i>
                    <span>Extras</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="code-editor.html">Code editor</a></li>
                    <li><a href="grids.html">Grids</a></li>
                    <li><a href="signin.html">Sign in</a></li>
                    <li><a href="signup.html">Sign up</a></li>
                </ul>
            </li>
        </ul>
    </div>

app/views/partials/_subnav.html.erb
<% if user_signed_in? %>
<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">
      <a href="javascript:;" class="subnav-toggle" data-toggle="collapse" data-target=".subnav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <i class="icon-reorder"></i>
      </a>
      <div class="collapse subnav-collapse">
        <ul class="mainnav">
          <% if current_user.role != "User" %>
            <li class="<%= 'active' if controller?('clients') %>">
              <%= link_to "<i class='icon-book'></i><span>Clients</span>".html_safe, clients_path %>
            </li>

            <li class="<%= 'active' if controller?('case_entries') && action?('index') %>">
              <%= link_to "<i class='icon-legal'></i><span>Case Entries</span>".html_safe, case_entries_path %>
            </li>

            <li class="<%= 'active' if controller?('lawyers') %>">
              <%= link_to "<i class='icon-briefcase'></i><span>Lawyers</span>".html_safe, lawyers_path %>
            </li>

            <li class="<%= 'active' if controller?('file_matters') %>">
              <%= link_to "<i class='icon-archive'></i><span>File/Matters</span>".html_safe, file_matters_path %>
            </li>

            <li class="<%= 'active' if controller?('case_entries') && action?('search_entry') %>">
              <%= link_to "<i class='icon-dashboard'></i><span>Timesheet</span>".html_safe, search_entry_path %>
            </li>

            <li class="<%= 'active' if controller?('account/users') %>">
              <%= link_to "<i class='icon-group'></i><span>Users</span>".html_safe, account_users_path %>
            </li>

            <li class="<%= 'active' if controller?('graphs') %>">
              <%= link_to "<i class='icon-bar-chart'></i><span>Graphs</span>".html_safe, graphs_path %>
            </li>
          <% else %>
            <li class="<%= 'active' if controller?('case_entries') && action?('index') %>">
              <%= link_to "<i class='icon-legal'></i><span>Case Entries</span>".html_safe, case_entries_path %>
            </li>

            <li class="<%= 'active' if controller?('file_matters') %>">
              <%= link_to "<i class='icon-archive'></i><span>File/Matters</span>".html_safe, file_matters_path %>
            </li>
          <% end %>
        </ul>
      </div> <!-- /.subnav-collapse -->
    </div> <!-- /container -->
  </div> <!-- /subnavbar-inner -->
</div>
<% end %>

app/views/partials/_topbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">

  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <i class="icon-cog"></i>
      </button>
      <a class="navbar-brand" href="/">Logo Here</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">

          <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-cog"></i>
            Settings
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <li><a href="./account.html">Account Settings</a></li>
            <li><a href="javascript:;">Privacy Settings</a></li>
            <li class="divider"></li>
            <li><a href="javascript:;">Help</a></li>
          </ul>

        </li>

        <li class="dropdown">

          <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-user"></i> 
            Nad Flores
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <li><a href="javascript:;">My Profile</a></li>
            <li><a href="javascript:;">My Groups</a></li>
            <li class="divider"></li>
            <li><a href="javascript:;">Logout</a></li>
          </ul>

        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div> <!-- /.container -->
</nav>