config/routes.rb
Case2::Application.routes.draw do
  devise_for :users
  
  namespace :account do
    resources :users 
  end

  resources :clients
  resources :lawyers
  resources :file_matters do
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_title"
    end
  end
  resources :case_entries do
  	# get :autocomplete_file_matter_file_code, :on => :collection
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_case_number"
    end
      
  end

  resources :admin_side
  resources :graphs do 
    collection do 
      get "ac_file_code"
      get "ac_client_gr"
    end
  end
  resources :calls do
    collection do 
      get "ac_client"
    end
  end

  resources :printouts do
    collection do 
      get "ac_file_code"
    end

  end
  
  resources :notifications do
    collection do
      get "list_notifications"
      get "notified"
    end
  end

  resources :schedules
  resources :practice_tables 
  resources :doc_abbreviations
  resources :file_namings
  resources :case_entry_billings
  
  root :to => 'case_entries#new'
  
  # ajax
  get 'pages/update_songs', :as => 'update_songs'
  get 'pages/update_songs2', :as => 'update_songs2'
  get 'pages/parse_client', :as => 'parse_client'
  get 'pages/update_case_entry', :as => 'update_case_entry'
  get 'pages/printouts_entry', :as => 'printouts_entry'
  get 'pages/update_cases', :as => 'update_cases'
  get 'pages/update_search_form', :as => 'update_search_form'
  get 'pages/schedule_entry', :as => 'schedule_entry'
  get 'pages/add_client_code', :as => 'add_client_code'
  get 'pages/pick_filematter', :as => 'pick_filematter'
  get 'pages/add_practice_code', :as => 'add_practice_code'
  get 'pages/select_file_matters', :as => 'select_file_matters'
  get 'pages/select_status', :as => 'select_status'
  get 'pages/update_status_assinged', :as => 'update_status_assinged'
  

  # search
  # match '/all_employees_list', :to => 'labor_hours#all_employees_list'
  match 'search_entry', :to  => 'case_entries#search_entry'
  match 'search_entry_multi', :to  => 'case_entries#search_entry_multi'
  match 'search_entry_graph', :to  => 'graphs#search_entry_graph'
  match 'search_entry_other_graph', :to  => 'graphs#search_entry_other_graph'
  match 'search_entry_other_graph2', :to  => 'graphs#search_entry_other_graph2'
  match 'exclude_billing', :to =>  'case_entries#exclude_billing'
  match 'modify_case_entry', :to =>  'case_entries#modify_case_entry'
  match 'case_entries/search' => 'case_entries#search_entry'
  match 'file_matters/search' => 'file_matters#search_entry'
  match '/admin_side/search' => 'admin_side#index'
  match 'activate_account', :to =>  'account/users#activate_account'
  match 'deactivate_account', :to =>  'account/users#deactivate_account'
  match 'activate_lawyer', :to =>  'lawyers#activate_account'
  match 'deactivate_lawyer', :to =>  'lawyers#deactivate_account'
  match 'exclude_printout', :to =>  'printouts#exclude_printout'
  match 'include_printout', :to =>  'printouts#include_printout'
  match 'search_by_client', :to => 'printouts#search_by_client'
  match 'weekly_view', :to => 'schedules#weekly_view'
  match 'daily_view', :to => 'schedules#daily_view'
  

  # recent modification for filtering data in case entries
  match 'filter_by_workload', :to => 'case_entries#filter_by_workload'
  match 'filter_by_client_code', :to => 'case_entries#filter_by_client_code'
  match 'filter_by_practice_code', :to => 'case_entries#filter_by_practice_code'
  match 'filter_by_period', :to => 'case_entries#filter_by_period'
  match 'filter_by_compared_workload', :to => 'case_entries#filter_by_compared_workload'

  # for timesheet additional tab and function
  match 'search_billed_entry', :to  => 'case_entries#search_billed_entry'
  match 'mark_as_billed', :to  => 'case_entries#mark_as_billed'

  match 'view_billing_generated', :to => 'case_entry_billings#view_billing_generated'
  match 'assigned_lawyer_filematters', :to => 'pages#assigned_lawyer_filematters'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :client, :lawyer_id, :schedule_date, :schedule_time, 
                  :status, :purpose, :sched_title, :start_time, :end_time,
                  :client_id, :file_matter_id, :file_matter_case, :case_title,
                  :ref_no
  has_many :clients
  belongs_to :lawyer
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	helper_method :sort_column, :sort_direction
  def index
    # if params[:schedule].present?
    #   @schedules = Schedule.where("name ILIKE ?", "#{params[:schedule]}").paginate(:page => params[:page], :per_page => 50).order(sort_column + " " + sort_direction)
    # else  
    #   @schedules = Schedule.paginate(:page => params[:page], :per_page => 50).order(sort_column + " " + sort_direction)
    # end
    if current_user.lawyer_id.present?
	  	@schedules = Schedule.where(lawyer_id: current_user.lawyer_id)
	    respond_to do |format|
	      format.html # index.html.erb
	    end
	  else  
	   	@schedules = Schedule.order("schedule_time ASC")
	    respond_to do |format|
	      format.html # index.html.erb
	    end
	  end
  end

  def weekly_view
    if current_user.lawyer_id.present?
	  	@schedules = Schedule.where(lawyer_id: current_user.lawyer_id)
	    respond_to do |format|
	      format.html # index.html.erb
	    end
	  else  
	   	@schedules = Schedule.order("schedule_time ASC")
	    respond_to do |format|
	      format.html # index.html.erb
	    end
	  end
  end

  def daily_view
    if current_user.lawyer_id.present?
    	if params[:date].present?
        if params[:file_matter_id]
          @schedules = Schedule.where(lawyer_id: current_user.lawyer_id).where(start_time: params[:date]).where(file_matter_id: params[:file_matter_id])
          respond_to do |format|
            format.html # index.html.erb
          end
        else  
  		  	@schedules = Schedule.where(lawyer_id: current_user.lawyer_id).where(start_time: params[:date])
  		    respond_to do |format|
  		      format.html # index.html.erb
  		    end
        end
		  end
	  else  
	   	@schedules = Schedule.where(start_time: params[:date]).order("schedule_time ASC")
	    respond_to do |format|
	      format.html # index.html.erb
	    end
	  end
  end

  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
      	if params[:ce]
      		format.html { redirect_to new_case_entry_path, notice: 'Schedule was successfully created.' }
        	# format.json { render json: @schedule, status: :created, location: @schedule }
      	else
        	format.html { redirect_to schedules_path, notice: 'Schedule was successfully created.' }
        	format.json { render json: @schedule, status: :created, location: @schedule }
      	end
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to schedules_path, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to @schedule }
      format.json { head :no_content }
    end
  end

  def list_schedules
    # @lists = Schedule.find(params[:schedule_id])
  end
  
  def notified
    
    @schedule = Schedule.find(params[:id])
    @schedule.update_attributes(:notified => true)
    respond_to do |format|
      format.html { redirect_to request.referrer, alert: 'You have beend notified.' }
      format.json { head :no_content }
    end
  end

  private
  
  def sort_column
    Schedule.column_names.include?(params[:sort]) ? params[:sort] : "schedule_title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= simple_form_for @schedule, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="panel panel-primary">
		<div class="row">
    	<div class="span10">
	    	<div class="row">
					<div class="span3">
						<%#= f.input :ref_no, :label => 'Reference Number', :required => true %>
						<%= f.input :sched_title, :collection => ["Deadline", "Hearing", "Meeting", "Telecon"] , :label =>  "Sched Title:" , :include_blank => false, :required => true  %>
						<%#= f.input :case_title, :label => 'Case Title' %>
						<%#= f.input :client, :label => 'Client' %>
					</div>	
					<div class="span3">
						<%#= f.input :ref_no, :label => 'Reference Number', :required => true %>
						<%= f.label :ref_no, "File Reference Number:" %>
						<%= f.autocomplete_field :ref_no, ac_file_code_printouts_path, :required => true, :class => "entry_date" %>
						<%#= f.input :case_title, :label => 'Case Title' %>
						<%#= f.input :client, :label => 'Client' %>
					</div>	
					<div class="span4">
						<%= f.label :file_matter_case, "Case No.:"%>
					  <%= f.text_field :file_matter_case,:readonly => true, :style => "width: 100%;" %>
					</div>
					<div class="span10">
						<%= f.label :client, "Client:"%>
					  <%= f.text_field :client, :readonly => true, :style => "width: 100%;" %>
					</div>
					<div class="span10">
						<%= f.hidden_field :client_id %>
						
						<%= f.hidden_field :file_matter_id %>
					  <%= f.label :case_title, "Case Title:"%>
					  <%= f.text_field :case_title,:readonly => true, :style => "width: 100%;" %>
					</div>	
					<div class="span3">
						<%#= f.label :lawyer_id, "Assigned to Lawyer:"%>
					  <% if current_user.lawyer_id.nil? %>
					  	<%= f.input :lawyer_id, :collection => Lawyer.all.map {|u| [u.full_name, u.id] },  :include_blank => false, :prompt => "---", :required => true %>
					  <% else %>
					  	<%= f.input :lawyer_id, :collection => Lawyer.where(id: current_user.lawyer_id).map {|u| [u.full_name, u.id] },  :include_blank => false, :required => true %>
					  <% end %>
					</div>
					<div class="span3">
						<%= f.label :start_time, "Schedule Date:"%>
					  <%= f.text_field :start_time, :id => 'datepicker123', :style => "width: 100%;" %>
					</div>
					<div class="span2">
						<%= f.label :schedule_time, "Time Start:"%>
					  <%= f.text_field :schedule_time, :id => 'sched_time', :style => "width: 100%;" %>
					</div>
					<div class="span2">
						<%= f.label :schedule_time, "Time End:"%>
					  <%= f.text_field :schedule_time, :id => 'sched_time2', :style => "width: 100%;" %>
					</div>
					<div class="span10">
<!-- 						<%#= f.hidden_field :client_id %>
						<%#= f.hidden_field :file_matter_id %> -->
					  <%= f.label :purpose, "Purpose:"%>
					  <%= f.text_area :purpose, :rows => 8, :cols => 30, :class => "text_area", :style => "width: 100%;" %>
					</div>
					<div class="span10">
							<br/>
					    <div class="pull right">
						    <%= f.button :submit, 'Create Entry', :class => 'btn btn-primary' %>
						    <% if params[:ce] %>
									<%= hidden_field_tag :ce, value: params[:ce] %>
									<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
						                new_case_entry_path, :class => 'btn' %>
								<% else %>
									<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
						                schedules_path, :class => 'btn' %>
								<% end %>
						    
					    </div>
					  	<br/>
				 	</div>
				</div>
			</div>
			<br/>
			<br/>
		</div>
	</div>
<% end %>

					

<script>
	$(function() {
		$('#datepicker123').datepicker({format: 'yyyy-mm-dd'});
		$('#sched_time').ptTimeSelect();
		$('#sched_time2').ptTimeSelect();
	});

	$(document).ready(function() {
		$('#schedule_ref_no').blur(function(){
      $.ajax({
        url: "<%= schedule_entry_path %>",
        data: {
          printout_file_matter_id : $('#schedule_ref_no').val()
        },
        dataType: "script"
      });
    });
  });  

</script>

app/views/schedules/daily_view.html.erb
<% @meeting = @schedules.where(sched_title: "Meeting") %>
<% @hearing = @schedules.where(sched_title: "Hearing") %>
<% @deadline = @schedules.where(sched_title: "Deadline") %>
<br>
  
<div class="panel">
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Search</div>
    <div class="row">

      <div class="span11">
      <%= form_for daily_view_path, :method => 'get' do %>
          <div class="span3">    
              File Reference Code:&nbsp;&nbsp;
              <%= autocomplete_field_tag :file_matter_id, nil, ac_file_code_printouts_path, :required => false %>
          </div>
          <div class="span3">    
              Date From:&nbsp;&nbsp;
              <%= text_field_tag :beginning_date, nil,  :id => "datepicker_beg"%>
          </div>
          <div class="span3">
              Date To:&nbsp;&nbsp;
              <%= text_field_tag :ending_date, nil,  :id => "datepicker_end"%>
              <%= hidden_field_tag :date, params[:date]%>
          </div>
          <div class="span10">
            <div class="pull-right">
                  <%= submit_tag "Search" %>
            </div>
          </div>
          <div class="span10">
            
          </div>
      <% end %>
      </div>
    </div>
  </div>
  <br>
  <br>
<% if @meeting.count != 0 || @meeting.count.nil? %>
  <div class="panel-heading"><h3>Schedules - Daily View</h3></div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading"><h4>Meeting</h4></div>
      <table class="table table-striped">      
        <tr>
          <th>Lawyer Name</th>
          <th>Time</th>
          <th>Client</th>
          <th>File Reference No.</th>
          <th></th>
        </tr>
        <% @schedules.where(sched_title: "Meeting").each do |schedule| %>
          <% @filemattercode = FileMatter.select(:file_code).where(id: schedule.file_matter_id) %>
          <tr>
            <td><%= schedule.lawyer.full_name %></td>
            <td><%= schedule.schedule_time %></td>
            <td><%= schedule.client %></td>
            <td><%= @filemattercode.blank? ? '' : @filemattercode.last.file_code %></td>
            <td><%= link_to "View", schedule_path(schedule), title: 'View Schedule Details' %></td>    
            </td>
          </tr>
        <% end %>
      </table>
  </div>
  <br>
<% end %>

<% if @hearing.count != 0 || @hearing.count.nil? %>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading"><h4>Hearing</h4></div>
    <table class="table table-striped">      
        <tr>
          <th>Lawyer Name</th>
          <th>Time</th>
          <th>Client</th>
          <th>File Reference No.</th>
          <th></th>
        </tr>
        <% @schedules.where(sched_title: "Hearing").each do |schedule| %>
          <% @filemattercode = FileMatter.select(:file_code).where(id: schedule.file_matter_id) %>
          <tr>
            <td><%= schedule.lawyer.full_name %></td>
            <td><%= schedule.schedule_time %></td>
            <td><%= schedule.client %></td>
            <td><%= @filemattercode.blank? ? '' : @filemattercode.last.file_code %></td>
            <td><%= link_to "View", schedule_path(schedule), title: 'View Schedule Details' %></td>    
            </td>
          </tr>
        <% end %>
      </table>
  </div>
  <br>
<% end %>

<% if @deadline.count != 0 || @deadline.count.nil? %>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading"><h4>Deadline</h4></div>
    <table class="table table-striped">      
        <tr>
          <th>Lawyer Name</th>
          <th>Time</th>
          <th>Client</th>
          <th>File Reference No.</th>
          <th></th>
        </tr>
        <% @schedules.where(sched_title: "Deadline").each do |schedule| %>
          <% @filemattercode = FileMatter.select(:file_code).where(id: schedule.file_matter_id) %>
          <tr>
            <td><%= schedule.lawyer.full_name %></td>
            <td><%= schedule.schedule_time %></td>
            <td><%= schedule.client %></td>
            <td><%= @filemattercode.blank? ? '' : @filemattercode.last.file_code %></td>
            <td><%= link_to "View", schedule_path(schedule), title: 'View Schedule Details' %></td>    
            </td>
          </tr>
        <% end %>
      </table>
  </div>
<% end %>

</div>

<script>
  $(function() {
      $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
      $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
    });
</script>

app/views/schedules/edit.html.erb
<div class="page-header">
  <h3>Edit Schedule Entry</h3>
</div>
<div class="row">
	<div class="span12">
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/schedules/index.html.erb
<div class="panel">
  <div class="panel-heading"><h3>Schedules</h3></div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Monthly View</div>
    <br>
    <%= month_calendar events: @schedules do |date, schedules| %>
      <span><%= date.day %></span>
      <% if schedules.count != 0 %>
        <span class="pull-right">
          <%= link_to 'View', daily_view_path(date: date), :class => 'btn btn-mini btn-warning' %>
        </span>
      <% end %>  
      <% schedules.each do |schedule| %>
        <div>
          <%= link_to schedule.sched_title, schedule_path(schedule), title: 'View Schedule Details' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="page-header">
  <h3>Schedule Entry Form</h3>
</div>
<div class="row">
	<div class="span12">
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/schedules/show.html.erb
<div class="page-header">
  <h3>Current Schedule</h3>
</div>
<div class="row">
	<div class="span10">
		<div class="panel panel-primary">
			<div class="row">
    		<div class="span2">
	    		<h4>Client:</h4> 
				</div>
				<div class="span5">
	    		<%= @schedule.client %> 
				</div>
			</div>
			<div class="row">
				<div class="span2">
	    		<h4>Sched Title:</h4> 
				</div>
				<div class="span5">
	    		<%= @schedule.sched_title %> 
				</div>
			</div>
			<div class="row">
				<div class="span2">
	    		<h4>Date Schedule:</h4> 
				</div>
				<div class="span5">
	    		<%= @schedule.start_time %> 
				</div>
			</div>
			<div class="row">
				<div class="span2">
	    		<h4>Time:</h4> 
				</div>
				<div class="span5">
	    		<%= @schedule.schedule_time %> 
				</div>
			</div>
			<div class="row">
				<div class="span2">
	    		<h4>Assigned Lawyer:</h4> 
				</div>
				<div class="span5">
	    		<%= @schedule.lawyer.full_name %> 
				</div>
			</div>
			<div class="row">
				<div class="span2">
	    		<h4>Purpose:</h4> 
				</div>
				<div class="span5">
	    		<%= @schedule.purpose %> 
				</div>
			</div>
			<br>
			<div class="row">
				<div class="span10 full-right">
	    		<%= link_to '<< Back', schedules_path, :class => 'btn btn-warning' %>
	    		<%= link_to 'Edit', edit_schedule_path(@schedule), :class => 'btn btn-success' %>
					<%= link_to 'Delete', schedule_path(@schedule), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' %>
				</div>
			</div>
			<br>
		</div>
	</div>
</div>

app/views/schedules/weekly_view.html.erb
<div class="panel">
  <div class="panel-heading"><h3>Schedules</h3></div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Weekly View</div>
    <br>
    <%= calendar number_of_days: 7, events: @schedules do |date, schedules| %>
      <strong><%= date.day %></strong>
      <br>

      <% x = date.beginning_of_day + 6.hour %>
      <% y = (date.end_of_day - 4.hour) - 59.minute %>
      
      <table class="table table-striped">
        
          <!-- <td>
            <% x = x + 1.hour %>
            <%= current_time = x.strftime("%I:%M %p") %>
          </td> -->
          <% schedules.each do |schedule| %>
            <tr>
              <td>
                <p><%= schedule.schedule_time %></p>
                <p><%= link_to schedule.sched_title, schedule_path(schedule), title: 'View Schedule Details' %></p>    
              </td>
            </tr>
          <% end %>
      </table>
    <% end %>
  </div>
</div>