config/routes.rb
Case2::Application.routes.draw do
  devise_for :users
  
  namespace :account do
    resources :users 
  end

  resources :clients
  resources :lawyers
  resources :file_matters do
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_title"
    end
  end
  resources :case_entries do
  	# get :autocomplete_file_matter_file_code, :on => :collection
    collection do 
      get "autocomplete_file_matter_file_code"
      get "autocomplete_file_matter_case_number"
    end
      
  end

  resources :admin_side
  resources :graphs do 
    collection do 
      get "ac_file_code"
      get "ac_client_gr"
    end
  end
  resources :calls do
    collection do 
      get "ac_client"
    end
  end

  resources :printouts do
    collection do 
      get "ac_file_code"
    end

  end
  
  resources :notifications do
    collection do
      get "list_notifications"
      get "notified"
    end
  end

  resources :schedules
  resources :practice_tables 
  resources :doc_abbreviations
  resources :file_namings
  resources :case_entry_billings
  
  root :to => 'case_entries#new'
  
  # ajax
  get 'pages/update_songs', :as => 'update_songs'
  get 'pages/update_songs2', :as => 'update_songs2'
  get 'pages/parse_client', :as => 'parse_client'
  get 'pages/update_case_entry', :as => 'update_case_entry'
  get 'pages/printouts_entry', :as => 'printouts_entry'
  get 'pages/update_cases', :as => 'update_cases'
  get 'pages/update_search_form', :as => 'update_search_form'
  get 'pages/schedule_entry', :as => 'schedule_entry'
  get 'pages/add_client_code', :as => 'add_client_code'
  get 'pages/pick_filematter', :as => 'pick_filematter'
  get 'pages/add_practice_code', :as => 'add_practice_code'
  get 'pages/select_file_matters', :as => 'select_file_matters'
  get 'pages/select_status', :as => 'select_status'
  get 'pages/update_status_assinged', :as => 'update_status_assinged'
  

  # search
  # match '/all_employees_list', :to => 'labor_hours#all_employees_list'
  match 'search_entry', :to  => 'case_entries#search_entry'
  match 'search_entry_multi', :to  => 'case_entries#search_entry_multi'
  match 'search_entry_graph', :to  => 'graphs#search_entry_graph'
  match 'search_entry_other_graph', :to  => 'graphs#search_entry_other_graph'
  match 'search_entry_other_graph2', :to  => 'graphs#search_entry_other_graph2'
  match 'exclude_billing', :to =>  'case_entries#exclude_billing'
  match 'modify_case_entry', :to =>  'case_entries#modify_case_entry'
  match 'case_entries/search' => 'case_entries#search_entry'
  match 'file_matters/search' => 'file_matters#search_entry'
  match '/admin_side/search' => 'admin_side#index'
  match 'activate_account', :to =>  'account/users#activate_account'
  match 'deactivate_account', :to =>  'account/users#deactivate_account'
  match 'activate_lawyer', :to =>  'lawyers#activate_account'
  match 'deactivate_lawyer', :to =>  'lawyers#deactivate_account'
  match 'exclude_printout', :to =>  'printouts#exclude_printout'
  match 'include_printout', :to =>  'printouts#include_printout'
  match 'search_by_client', :to => 'printouts#search_by_client'
  match 'weekly_view', :to => 'schedules#weekly_view'
  match 'daily_view', :to => 'schedules#daily_view'
  

  # recent modification for filtering data in case entries
  match 'filter_by_workload', :to => 'case_entries#filter_by_workload'
  match 'filter_by_client_code', :to => 'case_entries#filter_by_client_code'
  match 'filter_by_practice_code', :to => 'case_entries#filter_by_practice_code'
  match 'filter_by_period', :to => 'case_entries#filter_by_period'
  match 'filter_by_compared_workload', :to => 'case_entries#filter_by_compared_workload'

  # for timesheet additional tab and function
  match 'search_billed_entry', :to  => 'case_entries#search_billed_entry'
  match 'mark_as_billed', :to  => 'case_entries#mark_as_billed'

  match 'view_billing_generated', :to => 'case_entry_billings#view_billing_generated'
  match 'assigned_lawyer_filematters', :to => 'pages#assigned_lawyer_filematters'
end

app/models/printout.rb
class Printout < ActiveRecord::Base
  attr_accessible :ref_no, :entry_date, :case_title, :client, :document_name, :num_page, :num_copy, :paper_size, :client_id,
  								:file_matter_id, :file_matter_case, :lawyer_id, :times_amount, :entry_flag
end

app/controllers/printouts_controller.rb
class PrintoutsController < ApplicationController
  
  autocomplete :file_matter, :file_code, :full => true

	def index
    if params[:beginning_date].present? && params[:ending_date].present? || params[:file_matter_id].present?
      @beginning_date = params[:beginning_date]
      @ending_date = params[:ending_date]
      @file_code = params[:file_matter_id]
      args = {}
      if !@file_code.empty?
        @fm = FileMatter.find_by_file_code(@file_code)
        args.merge!(file_matter_id: @fm.id) 
        # @calls = Call.where(args).paginate(:page => params[:page], :per_page => 50, :order => "call_date DESC")
      end  
        args.merge!(entry_date: params[:beginning_date]..params[:ending_date]) unless params[:beginning_date].blank?
        @printouts = Printout.where(args).paginate(:page => params[:page], :per_page => 50, :order => "entry_date ASC")
    elsif params[:beginning_date].present? && params[:ending_date].present? && params[:file_matter_id].present?
      @beginning_date = params[:beginning_date]
      @ending_date = params[:ending_date]
      @file_code = params[:file_matter_id]
      args = {}
      args.merge!(file_matter_id: @fm.id)
      args.merge!(entry_date: params[:beginning_date]..params[:ending_date]) unless params[:beginning_date].blank?
      @printouts = Printout.where(args).paginate(:page => params[:page], :per_page => 50, :order => "entry_date ASC")    
    else
      @beginning_date = Date.today.beginning_of_month.strftime('%b %d, %Y')
      @ending_date = Date.today.strftime('%b %d, %Y')
      args = {}
      args.merge!(entry_date: @beginning_date..@ending_date)
      @printouts = Printout.paginate(:page => params[:page], :per_page => 50, :order => "entry_date ASC")
    end
    @file_code = params[:file_matter_id]
    @file_matters =  @printouts.pluck(:file_matter_id).uniq
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calls }
      format.csv  { render :csv => @calls, :except => [:id] }
      format.pdf do 
        pdf = PrintEntriesPdf.new(@printouts, @beginning_date, @ending_date, @file_matters, @file_code)
        send_data pdf.render, filename: "Print Summary Report" + Date.today.to_s + ".pdf", disposition: "inline"
      end
    end
  end

  def show
    @printout = Printout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @printout }
    end
  end

  def new
    @printout = Printout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @printout }
    end
  end

  def edit
    @printout = Printout.find(params[:id])
  end

  def create
    @printout = Printout.new(params[:printout])

    respond_to do |format|
      if @printout.save
        format.html { redirect_to printouts_path, notice: 'Printout entry was successfully created.' }
        format.json { render json: printouts_path, status: :created, location: @printout }
      else
        format.html { render action: "new" }
        format.json { render json: @printout.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @printout = Printout.find(params[:id])

    respond_to do |format|
      if @printout.update_attributes(params[:printout])
        format.html { redirect_to printouts_path, notice: 'Printout entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @printout.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @printout = Printout.find(params[:id])
    @printout.destroy

    respond_to do |format|
      format.html { redirect_to printouts_path }
      format.json { head :no_content }
    end
  end

  def exclude_printout
    @printout = Printout.find params[:printout_id]
    @printout.entry_flag = false
    respond_to do |format|
      if @printout.save
        format.html { redirect_to printouts_path(params), notice: 'Entry excluded from the searh list.' }
        # format.json { render json: printouts_path, status: :created, location: @printout }
      else
        format.html { render action: "new" }
        format.json { render json: @printout.errors, status: :unprocessable_entity }
      end
    end

  end

  def include_printout
    @printout = Printout.find params[:printout_id]
    @printout.entry_flag = true
    respond_to do |format|
      if @printout.save
        format.html { redirect_to printouts_path(params), notice: 'Entry included in the search list.' }
        # format.json { render json: printouts_path, status: :created, location: @printouint }
      else
        format.html { render action: "new" }
        format.json { render json: @printout.errors, status: :unprocessable_entity }
      end
    end
  end

  def search_by_client
    if params[:beginning_date].present? && params[:ending_date].present? || params[:client_id].present?
      @beginning_date = params[:beginning_date]
      @ending_date = params[:ending_date]
      @client_id = params[:client_id]
      args = {}
      if !@client_id.empty?
        @cname = Client.find_by_name(@client_id)
        args.merge!(client_id: @cname.id)
        # @calls = Call.where(args).paginate(:page => params[:page], :per_page => 50, :order => "call_date DESC")
      end  
      args.merge!(entry_date: params[:beginning_date]..params[:ending_date]) unless params[:beginning_date].blank?
      @printouts = Printout.where(args).paginate(:page => params[:page], :per_page => 50, :order => "entry_date ASC")
    # elsif params[:beginning_date].present? && params[:ending_date].present? && params[:file_matter_id].present?
    #   @beginning_date = params[:beginning_date]
    #   @ending_date = params[:ending_date]
    #   @file_code = params[:file_matter_id]
    #   args = {}
    #   args.merge!(file_matter_id: @fm.id)
    #   args.merge!(entry_date: params[:beginning_date]..params[:ending_date]) unless params[:beginning_date].blank?
    #   @printouts = Printout.where(args).paginate(:page => params[:page], :per_page => 50, :order => "entry_date ASC")    
    else
      @beginning_date = Date.today.beginning_of_month.strftime('%b %d, %Y')
      @ending_date = Date.today.strftime('%b %d, %Y')
      args = {}
      args.merge!(entry_date: @beginning_date..@ending_date)
      @printouts = Printout.paginate(:page => params[:page], :per_page => 50, :order => "entry_date ASC")
    end
    
    @file_matters =  @printouts.pluck(:file_matter_id).uniq
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calls }
      format.csv  { render :csv => @calls, :except => [:id] }
      format.pdf do 
        pdf = PrintEntriesClientsPdf.new(@printouts, @beginning_date, @ending_date, @file_matters, @cname)
        send_data pdf.render, filename: "Print Summary Report" + Date.today.to_s + ".pdf", disposition: "inline"
      end
    end
  end

  def ac_file_code
    render json: FileMatter.select("distinct file_code as value").where("file_code ILIKE ?", "%#{params[:term]}%")
    # render json: AnnualProcurementPlan.select("distinct version as value").where("version ILIKE ?", "%#{params[:term]}%").where(:agency_id => current_user.agency.id)
  end



end

app/helpers/printouts_helper.rb
module PrintoutsHelper
end

app/views/printouts/_form.html.erb
<%= simple_form_for @printout, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="panel panel-primary">
		<div class="row">
    	<div class="span10">
	    	<div class="row">
					<div class="span2">
						<%#= f.input :ref_no, :label => 'Reference Number', :required => true %>
						<%= f.label :ref_no, "File Reference Number:" %>
						<%= f.autocomplete_field :ref_no, ac_file_code_printouts_path, :required => true, :class => "entry_date" %>
						<%#= f.input :case_title, :label => 'Case Title' %>
						<%#= f.input :client, :label => 'Client' %>
					</div>	
					<div class="span4">
						<%= f.label :client, "Client:"%>
					  <%= f.text_field :client, :readonly => true, :style => "width: 100%;" %>
					</div>
					<div class="span4">
						<%= f.label :file_matter_case, "Case No.:"%>
					  <%= f.text_field :file_matter_case,:readonly => true, :style => "width: 100%;" %>
					</div>
					<div class="span10">
						<%= f.hidden_field :client_id %>
						<%= f.hidden_field :file_matter_id %>
					  <%= f.label :case_title, "Case Title:"%>
					  <%= f.text_field :case_title,:readonly => true, :style => "width: 100%;" %>
					</div>

					
					<div class="span3">
						<%= f.label :entry_date, "Date fo Printing:", :required => true %>
						<%= f.text_field :entry_date, :id => 'datepicker123', :class => "entry_date" %>
					</div>
					<div class="span3">
	  				<%= f.input :document_name, :label => 'Document Name:' %>
					</div>
					<div class="span4">
						<%= f.input :num_page, :label => 'Number of Page:' %>
					</div>
					<div class="span3">
						<%= f.input :num_copy, :label => 'Number of Copy:' %>
					</div>
					<div class="span3">
						<%= f.input :paper_size, :label => 'Paper Size:' %>
					</div>
					<div class="span3">
						<%= f.input :times_amount, :label => 'Amount Per Pages:' %>
					</div>	
					<div class="span10">
							<br/>
					    <div class="pull right">
						    <%= f.button :submit, 'Create Entry', :class => 'btn btn-primary' %>
						    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
						                printouts_path, :class => 'btn' %>
					    </div>
					  	<br/>
				 	</div>
				</div>
			</div>
			<br/>
			<br/>
		</div>
	</div>
<% end %>

<script>
	$(function() {
		$('#datepicker123').datepicker({format: 'yyyy-mm-dd'});
	});

	$(document).ready(function() {
		$('#printout_ref_no').blur(function(){
      $.ajax({
        url: "<%= printouts_entry_path %>",
        data: {
          printout_file_matter_id : $('#printout_ref_no').val()
        },
        dataType: "script"
      });
    });
  });  

</script>

app/views/printouts/edit.html.erb
<div class="page-header">
  <h3>Modify Printout</h3>
</div>
<div class="row">
	<div class="span12">
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/printouts/index.html.erb
<div class="panel">
  <div class="panel-heading"><h3>Printout Entries</h3></div>
  <div class="panel">
    <%= link_to "Seach By File Reference Code", printouts_path, :class => 'btn btn-success'%>
    &nbsp;&nbsp;&nbsp;
    <%= link_to "Seach By Client", search_by_client_path, :class => 'btn btn-success'%>
  </div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Search</div>
    <div class="row">

      <div class="span11">
      <%= form_for printouts_path, :method => 'get' do %>
          <div class="span3">    
              File Reference Code:&nbsp;&nbsp;
              <%= autocomplete_field_tag :file_matter_id, nil, ac_file_code_printouts_path, :required => false %>
          </div>
          <div class="span3">    
              Date From:&nbsp;&nbsp;
              <%= text_field_tag :beginning_date, nil,  :id => "datepicker_beg"%>
          </div>
          <div class="span3">
              Date To:&nbsp;&nbsp;
              <%= text_field_tag :ending_date, nil,  :id => "datepicker_end"%>
          </div>
          <div class="span10">
            <div class="pull-right">
                  <%= submit_tag "Search" %>
            </div>
          </div>
          <div class="span10">
            
          </div>
      <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Printout Lists</div>
    <div class="row">
      <div class="span11">
        <div class="pull-left">
          <%= link_to "Create Entry",
            new_printout_path,
            :class => 'btn btn-primary' %>
        </div>
        <div class="pull-right" style="margin-right: -40px;">
          <%= link_to "Download as PDF <i class='icon-download-alt'></i>".html_safe, printouts_path(params.merge(format: 'pdf')), :class => "btn btn-primary", target: 'blank' %>   
        </div>
        <br/>
        <br/>
        <div class="row">
          <div class="span11">
            <table class="table table-striped" id="clients">
              <thead>
                <tr>
                  <th width="12%"><center>Date Entered</center></th>
                  <th width="12%"><center>File Reference No:</center></th>
                  <th width="11%"><center># of Copies</center></th>
                  <th width="10%"><center># of Pages</center></th>
                  <th width="30%"><center>Document Name</center></th>
                  <th width="15%"><center>Action</center></th>
                </tr>
              </thead>
              <tbody>
                <% @printouts.each do |printout| %>
                  <% @filemattercode = FileMatter.select(:file_code).where(id: printout.file_matter_id) %>
                  <tr>
                    <td><center><%= printout.entry_date %></center></td>
                    <td><center><%= @filemattercode.blank? ? '' : @filemattercode.last.file_code %></center></td>
                    <td><center><%= printout.num_copy %></center></td>
                    <td><center><%= printout.num_page %></center></td>
                    <td><center><%= printout.document_name %></center></td>
                    <td>
                      <%= link_to 'Edit',
                                  edit_printout_path(printout), :class => 'btn btn-mini' %>
                      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                  printout_path(printout),
                                  :method => :delete,
                                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                  :class => 'btn btn-mini btn-danger' %>
                      <% if printout.entry_flag? %>
                        <%= link_to 'Exclude', exclude_printout_path(params.merge(printout_id: printout.id)), :class => 'btn btn-mini btn-warning' %>
                      <% else %>
                        <%= link_to 'Include', include_printout_path(params.merge(printout_id: printout.id)), :class => 'btn btn-mini btn-info' %>
                      <% end %>            
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="pull-right">
              <%= will_paginate @printouts, :param_name => 'page', previous_label: "<i class='icon-chevron-left'></i>".html_safe, next_label: "<i class='icon-chevron-right'></i>".html_safe %>
            </div>
          </div>
        </div>
        <%= link_to "Create Entry",
                    new_printout_path,
                    :class => 'btn btn-primary' %>
        <br>
        <br>
      </div>  
    </div>
  </div>  
</div>
<script>
  $(function() {
    $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
    $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
  });  
</script>
<script>
    // $('#case_entries').dataTable( {
    //   "aaSorting": [[ 0, "desc" ]],
    //   "aoColumns": [
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": false, "bSortable": false }
    //   ],
    //   "sPaginationType": "bootstrap"
    // } );
    
    $(function() {
      $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
      $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
      $('#datepicker123').datepicker({format: 'yyyy-mm-dd'});
      $('#case_entry_time_spent_from').ptTimeSelect();
      $('#case_entry_time_spent_to').ptTimeSelect();
    });

    $(document).ready(function(){
      $('.case_entry_file_matter_id').blur(function(){
        var case_entry_value = $(this).val()
        var case_entry_id = $(this).attr('id')
        $.ajax({
          url: "<%= update_case_entry_path %>",
          data: {
            file_matter_id : case_entry_value,
            case_entry_id  : case_entry_id
          },
          dataType: "script"
          // success: function(data){
          //   console.log(data);
          // }
        });
      });
    });  
  </script> 

app/views/printouts/new.html.erb
<div class="page-header">
  <h3>Printout Entry Form</h3>
</div>
<div class="row">
	<div class="span12">
		<%= render :partial => 'form' %>
	</div>
</div>

app/views/printouts/search_by_client.html.erb
<div class="panel">
  <div class="panel-heading"><h3>Printout Entries</h3></div>
  <div class="panel">
    <%= link_to "Seach By File Reference Code", printouts_path, :class => 'btn btn-success'%>
    &nbsp;&nbsp;&nbsp;
    <%= link_to "Seach By Client", search_by_client_path, :class => 'btn btn-success'%>
  </div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Search</div>
    <div class="row">

      <div class="span11">
      <%= form_for search_by_client_path, :method => 'get' do %>
          <div class="span3">    
              Client:&nbsp;&nbsp;
              <%= autocomplete_field_tag :client_id, nil, ac_client_gr_graphs_path, :required => false %>
          </div>
          <div class="span3">    
              Date From:&nbsp;&nbsp;
              <%= text_field_tag :beginning_date, nil,  :id => "datepicker_beg"%>
          </div>
          <div class="span3">
              Date To:&nbsp;&nbsp;
              <%= text_field_tag :ending_date, nil,  :id => "datepicker_end"%>
          </div>
          <div class="span10">
            <div class="pull-right">
                  <%= submit_tag "Search" %>
            </div>
          </div>
          <div class="span10">
            
          </div>
      <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-primary panel-heading">Printout Lists</div>
    <div class="row">
      <div class="span11">
        <div class="pull-right" style="margin-right: -40px;">
          <%= link_to "Download as PDF <i class='icon-download-alt'></i>".html_safe, search_by_client_path(params.merge(format: 'pdf')), :class => "btn btn-primary", target: 'blank' %>   
        </div>
        <br/>
        <br/>
        <div class="row">
          <div class="span11">
            <table class="table table-striped" id="clients">
              <thead>
                <tr>
                  <th width="12%"><center>Date Entered</center></th>
                  <th width="12%"><center>File Reference No:</center></th>
                  <th width="11%"><center># of Copies</center></th>
                  <th width="10%"><center># of Pages</center></th>
                  <th width="30%"><center>Document Name</center></th>
                  <th width="15%"><center>Action</center></th>
                </tr>
              </thead>
              <tbody>
                <% @printouts.each do |printout| %>
                  <% @filemattercode = FileMatter.select(:file_code).where(id: printout.file_matter_id) %>
                  <tr>
                    <td><center><%= printout.entry_date %></center></td>
                    <td><center><%= @filemattercode.blank? ? '' : @filemattercode.last.file_code %></center></td>
                    <td><center><%= printout.num_copy %></center></td>
                    <td><center><%= printout.num_page %></center></td>
                    <td><center><%= printout.document_name %></center></td>
                    <td>
                      <%= link_to 'Edit',
                                  edit_printout_path(printout), :class => 'btn btn-mini' %>
                      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                                  printout_path(printout),
                                  :method => :delete,
                                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                  :class => 'btn btn-mini btn-danger' %>
                      <% if printout.entry_flag? %>
                        <%= link_to 'Exclude', exclude_printout_path(params.merge(printout_id: printout.id)), :class => 'btn btn-mini btn-warning' %>
                      <% else %>
                        <%= link_to 'Include', include_printout_path(params.merge(printout_id: printout.id)), :class => 'btn btn-mini btn-info' %>
                      <% end %>            
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            
          </div>
        </div>
        
        <br>
      </div>  
    </div>
  </div>  
</div>
<script>
  $(function() {
    $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
    $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
  });  
</script>
<script>
    // $('#case_entries').dataTable( {
    //   "aaSorting": [[ 0, "desc" ]],
    //   "aoColumns": [
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": true, "bSortable": true },
    //     { "bSearchable": false, "bSortable": false }
    //   ],
    //   "sPaginationType": "bootstrap"
    // } );
    
    $(function() {
      $('#datepicker_beg').datepicker({format: 'yyyy-mm-dd'});
      $('#datepicker_end').datepicker({format: 'yyyy-mm-dd'});
      $('#datepicker123').datepicker({format: 'yyyy-mm-dd'});
      $('#case_entry_time_spent_from').ptTimeSelect();
      $('#case_entry_time_spent_to').ptTimeSelect();
    });

    $(document).ready(function(){
      $('.case_entry_file_matter_id').blur(function(){
        var case_entry_value = $(this).val()
        var case_entry_id = $(this).attr('id')
        $.ajax({
          url: "<%= update_case_entry_path %>",
          data: {
            file_matter_id : case_entry_value,
            case_entry_id  : case_entry_id
          },
          dataType: "script"
          // success: function(data){
          //   console.log(data);
          // }
        });
      });
    });  
  </script> 